---
micronaut:
  http:
    services:
      auth:
        urls:
          - ${AUTH_BASE_URL:`http://localhost:8080`}
  security:
    token:
      enabled: true
      jwt:
        enabled: true
        signatures:
          jwks:
            unity:
              url: ${AUTH_JWKS:`https://localhost:8081/keys`}
    redirect:
      login-success: http://localhost:3000
      login-failure: http://localhost:3000/?login-failed=true
      logout: http://localhost:8080
  server:
    cors:
      enabled: true
      configurations:
        allowedOrigins:
          - http://localhost:3000
          - localhost:3000
          - http://127.0.0.1:3000
---
app:
  service-id: ${LIBRE311_SERVICE_ID:1}
